sudo: false

before_script:
  # cmake
  - wget --no-check-certificate http://www.cmake.org/files/v3.3/cmake-3.3.0-Linux-x86_64.tar.gz -O cmake.tar.gz
  - tar -xzf cmake.tar.gz -C $HOME
  - export PATH=$HOME/cmake-3.3.0-Linux-x86_64/bin:$PATH
  - cmake --version
  # prepare
  - mkdir build
  - cd build
  - cmake ..

script: make
